sudo: true
language: generic
addons:
  ssh_known_hosts: 104.236.23.209
before_install:
- openssl aes-256-cbc -K $encrypted_1eb7a557f43e_key -iv $encrypted_1eb7a557f43e_iv
  -in deploy-key.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x scripts/deploy.sh && scripts/deploy.sh
  on:
    branch: master
